# Generated by Django 4.1.3 on 2025-07-03 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('day', models.CharField(max_length=15)),
                ('time', models.TimeField()),
                ('image', models.ImageField(upload_to='events/')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
